#!/usr/bin/env python3
"""Compare Agent target-position signals against a true buy-and-hold baseline."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import pandas as pd


PROJECT_DIR = Path(__file__).resolve().parent


def infer_from_signal_filename(path: Path) -> tuple[str | None, str | None, str | None]:
    match = re.search(
        r"signals_([^_]+)_(\d{4}-\d{2}-\d{2})_(\d{4}-\d{2}-\d{2})(?:_[^.]*)?\.csv$",
        path.name,
    )
    if not match:
        return None, None, None
    return match.group(1), match.group(2), match.group(3)


def build_buy_and_hold_signals(
    *,
    source_signals: Path,
    output_path: Path,
    target_position: float,
    strategy_name: str,
) -> Path:
    """Create a one-shot buy-and-hold signal on the first agent signal date."""
    source_signals = source_signals.expanduser().resolve()
    output_path = output_path.expanduser().resolve()

    df = pd.read_csv(source_signals)
    required = {"date", "ticker"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Source signal file missing required columns: {sorted(missing)}")
    if df.empty:
        raise ValueError("Source signal file is empty")

    first = df.sort_values("date").iloc[0]

    out = pd.DataFrame(
        [
            {
                "date": first["date"],
                "ticker": first["ticker"],
                "status": "baseline",
                "error_message": "",
                "action": "买入并持有",
                "confidence": 1.0,
                "risk_score": 0.0,
                "target_price": "",
                "action_score": target_position,
                "score": target_position,
                "target_position": float(target_position),
                "reasoning": f"{strategy_name}: initial target_position={target_position:.2f}; no rebalancing after entry",
            }
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False, encoding="utf-8")
    return output_path


def find_single_file(directory: Path, pattern: str) -> Path:
    matches = sorted(directory.glob(pattern))
    if not matches:
        raise FileNotFoundError(f"No file matching {pattern} in {directory}")
    return matches[-1]


def load_metrics(output_dir: Path, strategy: str) -> dict:
    metrics_path = find_single_file(output_dir, "qlib_signal_backtest_metrics_*.csv")
    trades_path = find_single_file(output_dir, "qlib_signal_backtest_trades_*.csv")

    metrics = pd.read_csv(metrics_path).iloc[0].to_dict()
    trades = pd.read_csv(trades_path)
    metrics["strategy"] = strategy
    metrics["trades"] = len(trades)
    metrics["metrics_path"] = str(metrics_path)
    metrics["trades_path"] = str(trades_path)
    return metrics


def format_pct(value) -> str:
    try:
        return f"{float(value):.2%}"
    except (TypeError, ValueError):
        return "N/A"


def format_num(value) -> str:
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "N/A"


def format_comparison_markdown(metrics: pd.DataFrame, ticker: str) -> str:
    rows = [
        f"# {ticker} Agent vs Buy-and-Hold Baseline",
        "",
        "| strategy | total_return | annual_return | max_drawdown | Sharpe | volatility | turnover_sum | trades |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for _, row in metrics.iterrows():
        rows.append(
            "| {strategy} | {total_return} | {annual_return} | {max_drawdown} | {sharpe} | {volatility} | {turnover_sum} | {trades} |".format(
                strategy=row["strategy"],
                total_return=format_pct(row.get("total_return")),
                annual_return=format_pct(row.get("annual_return")),
                max_drawdown=format_pct(row.get("max_drawdown")),
                sharpe=format_num(row.get("sharpe")),
                volatility=format_pct(row.get("volatility")),
                turnover_sum=format_num(row.get("turnover_sum")),
                trades=int(row.get("trades", 0)),
            )
        )

    rows.extend(
        [
            "",
            "## Reading",
            "",
            "- `agent` tests the dynamic target-position signal generated by TradingAgents.",
            "- `buy_hold_100` buys the stock once at the first executable trading step and then holds it without rebalancing.",
            "- Compare Sharpe and max drawdown together with total return; higher return alone is not enough if drawdown or turnover is worse.",
        ]
    )
    return "\n".join(rows) + "\n"


def run_backtest(
    *,
    signals: Path,
    ticker: str,
    provider_uri: str,
    output_dir: Path,
    init_cash: float,
    start: str | None,
    end: str | None,
    deal_price: str,
    open_cost: float,
    close_cost: float,
    min_cost: float,
) -> None:
    cmd = [
        sys.executable,
        str(PROJECT_DIR / "backtest_existing_signals_qlib.py"),
        "--signals",
        str(signals),
        "--ticker",
        ticker,
        "--provider-uri",
        provider_uri,
        "--output-dir",
        str(output_dir),
        "--init-cash",
        str(init_cash),
        "--deal-price",
        deal_price,
        "--open-cost",
        str(open_cost),
        "--close-cost",
        str(close_cost),
        "--min-cost",
        str(min_cost),
    ]
    if start:
        cmd.extend(["--start", start])
    if end:
        cmd.extend(["--end", end])

    subprocess.run(cmd, cwd=PROJECT_DIR, check=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare Agent signals with a one-shot 100% buy-and-hold baseline.")
    parser.add_argument("--signals", required=True, help="Agent signal CSV, preferably with target_position")
    parser.add_argument("--ticker", default=None, help="Ticker. Inferred from signal filename if omitted.")
    parser.add_argument("--start", default=None, help="Backtest start date. Inferred by backtest script if omitted.")
    parser.add_argument("--end", default=None, help="Backtest end date. Inferred by backtest script if omitted.")
    parser.add_argument("--provider-uri", required=True, help="Qlib provider_uri")
    parser.add_argument("--output-dir", required=True, help="Directory for comparison outputs")
    parser.add_argument("--init-cash", type=float, default=1_000_000.0)
    parser.add_argument("--deal-price", choices=["open", "close"], default="close")
    parser.add_argument("--open-cost", type=float, default=0.0005)
    parser.add_argument("--close-cost", type=float, default=0.0015)
    parser.add_argument("--min-cost", type=float, default=5.0)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    signals = Path(args.signals).expanduser().resolve()
    ticker, inferred_start, inferred_end = infer_from_signal_filename(signals)
    ticker = args.ticker or ticker
    if not ticker:
        raise ValueError("Ticker was not provided and could not be inferred from --signals")

    start = args.start or inferred_start
    end = args.end or inferred_end
    output_dir = Path(args.output_dir).expanduser().resolve()
    signal_dir = output_dir / "signals"
    backtest_dir = output_dir / "backtests"
    output_dir.mkdir(parents=True, exist_ok=True)

    baseline_100 = build_buy_and_hold_signals(
        source_signals=signals,
        output_path=signal_dir / f"signals_{ticker}_{start or 'start'}_{end or 'end'}_buy_hold_100.csv",
        target_position=1.0,
        strategy_name="buy_hold_100",
    )

    strategies = [
        ("agent", signals),
        ("buy_hold_100", baseline_100),
    ]

    rows = []
    for strategy, signal_path in strategies:
        strategy_output = backtest_dir / strategy
        run_backtest(
            signals=signal_path,
            ticker=ticker,
            provider_uri=args.provider_uri,
            output_dir=strategy_output,
            init_cash=args.init_cash,
            start=start,
            end=end,
            deal_price=args.deal_price,
            open_cost=args.open_cost,
            close_cost=args.close_cost,
            min_cost=args.min_cost,
        )
        rows.append(load_metrics(strategy_output, strategy))

    metrics_df = pd.DataFrame(rows)
    ordered_cols = [
        "strategy",
        "start_account",
        "end_account",
        "total_return",
        "annual_return",
        "max_drawdown",
        "sharpe",
        "volatility",
        "turnover_sum",
        "cost_sum",
        "trading_days",
        "trades",
        "metrics_path",
        "trades_path",
    ]
    metrics_df = metrics_df[[col for col in ordered_cols if col in metrics_df.columns]]

    csv_path = output_dir / f"comparison_{ticker}_{start or 'start'}_{end or 'end'}.csv"
    md_path = output_dir / f"comparison_{ticker}_{start or 'start'}_{end or 'end'}.md"
    metrics_df.to_csv(csv_path, index=False)
    md_path.write_text(format_comparison_markdown(metrics_df, ticker), encoding="utf-8")

    print("Baseline comparison finished")
    print(f"signals      : {signals}")
    print(f"ticker       : {ticker}")
    print(f"period       : {start} -> {end}")
    print(f"output_csv   : {csv_path}")
    print(f"output_md    : {md_path}")
    print(format_comparison_markdown(metrics_df, ticker))


if __name__ == "__main__":
    main()
